version: "3.9"
services:
  lamp:
    image: "ssmak/lamp:0.0.1"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./container_volume/www:/home/www
      